language: node_js
node_js:
  - lts/*
install:
  - npm install
script:
  - sh ./build.sh
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: .vuepress/dist
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  target_branch: master
  on:
    branch: edit
